-- MySQL Script generated by MySQL Workbench
-- 09/15/17 07:20:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `usuarios_Publicos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuarios_Publicos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `usuarios_Publicos` (
  `usuario` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`usuario`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `temas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `temas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `temas` (
  `titulo` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(100) NULL,
  `imagenes` VARCHAR(45) NULL,
  `usuarios_Publicos_usuario` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`titulo`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `subtemas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `subtemas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `subtemas` (
  `imagenes` VARCHAR(50) NOT NULL,
  `Descripcion` VARCHAR(100) NULL,
  `Documentos` VARCHAR(200) NULL,
  `temas_titulo` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`imagenes`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `imagenes_UNIQUE` ON `subtemas` (`imagenes` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `items` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `items` (
  `simuladores` VARCHAR(100) NOT NULL,
  `programas` VARCHAR(100) NULL,
  `paginas web` VARCHAR(200) NULL,
  `subtemas_imagenes` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`simuladores`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
